### ISSUE TITLE
Add {META}: {ABCMETA Token}

### ISSUE THREAD

**Issue by hanpeng168** [sameepsi/quickswap-default-token-list#127]
- [ ] I understand that token listing is not required to use the QuickSwap Interface with a token.
- [ ] I understand that filing an issue or adding liquidity does not guarantee addition to the QuickSwap default token list.
- [ ] I will not ping the Discord/Telegram about this listing request.

**Please provide the following information for your token.**

Token Address(Ethereum):
Token Address(Polygon):0xEDcFb6984a3c70501BAA8b7f5421Ae795ecC1496
Token Name (from contract): ABCMETA Token
Token Decimals (from contract): 8
Token Symbol (from contract): META
Pair Address of Token on QuickSwap: 0x75d4c0318aa29ad5dae306069131571540299421

Link to the official homepage of token:https://abcmeta.io
Link to CoinMarketCap or CoinGecko page of token:

**Comment by hanpeng168** [comment]
{
    "name": "ABCMETA Token",
    "address": "0xedcfb6984a3c70501baa8b7f5421ae795ecc1496",
    "symbol": "META",
    "decimals": 8,
    "chainId": 137,
    "logoURI": "https://bafkreidgbbysungh6ef2dx3n7hpcnlv5ilrnlyd6gmam67pz3n32pvrz6a.ipfs.nftstorage.link"
  }

**Comment by FreeEric007** [comment]
Please merge branch for me.
https://github.com/sameepsi/quickswap-default-token-list/pull/130
@sameepsi
